import mapActions from 'helpers/mapActions';

export default mapActions([
  'STORE_SELLER_COMPANY',
  'STORE_SELLER_COMPANY_INFO',
  'STORE_SELLER_LOGIN_INFO',
  'STORE_SELLER_NEXT_INFO',
  'STORE_SELLER_INFO_NEXT_STEP',
  'STORE_SELLER_STRIPE_INFO',
  'SUBMIT_SUBSCRIPTION',
  'SELLER_CURRENT_ACCOUNT',
  'CHANGE_STEP',
  'CHANGE_INFO_STEP',
  'CHANGE_PAYMENT_STEP',
  'STORE_INFO',
  //seller Products....
  'SUBMITTED_FORM',
  'PRODUCT_CREATED',
  'PRODUCT_LISTED',
  'PRODUCT_POPUP',
  'INSTAGRAM_CONNECT',
  'TWITTER_CONNECT',
  'LOGOUT'
], 'SELLER');
